version: "3"

services:
  buster-dev:
    build:
      context: ..
      dockerfile: buster/Dockerfile
      args:
        - USER=${USER}
    image: devbox-buster
    ports:
      - "22"
    volumes:
      - develop:/export

volumes:
  develop:
    external: true

