version: "3"

services:
  buster-dev:
    container_name: buster-dev
    build:
      context: ..
      dockerfile: buster/Dockerfile
      args:
        - USER=${USER}
    image: devbox-buster
    ports:
      - "22000:22"
    volumes:
      - develop:/export

volumes:
  develop:
    external: true
