apiVersion: v1
kind: ConfigMap
metadata:
  name: devbox
data:
  user: mjk
  dotfiles: https://github.com/masonkatz/dotfiles.git
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: devbox
spec:
  storageClassName: develop
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 32Gi
  hostPath:
    path: /data/devbox/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: devbox
spec:
  storageClassName: develop
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 32Gi
